apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: orchard-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/headphonebear/homehill
    targetRevision: main
    path: clusters/orchard/apps
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
