apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: orchard-apps
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/headphonebear/homehill
              revision: main
              directories:
                - path: clusters/orchard/apps/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/headphonebear/homehill
        targetRevision: main
        path: '{{path}}'
        directory:
          recurse: false
          include: 'argocd-app.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
