version: '3.8'

services:
  vaultwarden:
    image: headphonebear/vaultwarden-custom:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          - node.hostname == greenhouse
      labels:
        - "traefik.enable=true"
        # Main HTTP Router
        - "traefik.http.routers.vault.rule=Host(`vault.homehill.de`)"
        - "traefik.http.routers.vault.entrypoints=websecure"
        - "traefik.http.routers.vault.tls=true"
        - "traefik.http.routers.vault.tls.certresolver=hetzner"
        - "traefik.http.routers.vault.service=vault"
        # Main Service
        - "traefik.http.services.vault.loadbalancer.server.port=80"
        # WebSocket Router (für Notifications)
        - "traefik.http.routers.vault-ws.rule=Host(`vault.homehill.de`) && PathPrefix(`/notifications/hub`)"
        - "traefik.http.routers.vault-ws.entrypoints=websecure"
        - "traefik.http.routers.vault-ws.tls=true"
        - "traefik.http.routers.vault-ws.service=vault-ws"
        # WebSocket Service
        - "traefik.http.services.vault-ws.loadbalancer.server.port=3012"
    environment:
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=false
      - DOMAIN=https://vault.homehill.de
    volumes:
      - vault_data:/data
    networks:
      - traefik_traefik_proxy
    secrets:
      - vaultwarden_admin_token

networks:
  traefik_traefik_proxy:
    external: true

volumes:
  vault_data:

secrets:
  vaultwarden_admin_token:
    external: true
