# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ Monitoring Stack Application (Prometheus + Grafana)                       ║
# ║ Integrated with VictoriaMetrics for long-term storage                     ║
# ║ DEPLOYMENT ORDER: Deploy AFTER VictoriaMetrics (sync-wave: 0)             ║
# ╚════════════════════════════════════════════════════════════════════════════╝

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
    argocd.argoproj.io/sync-wave: "0"
    # WHY: Deploy AFTER VictoriaMetrics (which has sync-wave: -1)
    # Ensures VictoriaMetrics is ready before Prometheus starts remote-writing
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  # ╔──────────────────────────────────────────────────────────────────────────╗
  # ║ SOURCE: kube-prometheus-stack Helm chart                                 ║
  # ╚──────────────────────────────────────────────────────────────────────────╝
  source:
    repoURL: https://github.com/headphonebear/homehill.git
    targetRevision: new_season
    path: clusters/apps/monitoring/orchard
    # WHY: This path contains:
    # - Chart.yaml (with kube-prometheus-stack dependency)
    # - values.yaml (with remoteWrite to VictoriaMetrics configured)

    helm:
      releaseName: monitoring

      valueFiles:
        - values.yaml

  # ╔──────────────────────────────────────────────────────────────────────────╗
  # ║ DESTINATION: monitoring namespace                                        ║
  # ╚──────────────────────────────────────────────────────────────────────────╝
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
    # WHY: Dedicated namespace for all monitoring components
    # - Prometheus
    # - Grafana
    # - VictoriaMetrics
    # - Alertmanager (if enabled)
    # - Various exporters (node-exporter, kube-state-metrics)

  # ╔──────────────────────────────────────────────────────────────────────────╗
  # ║ SYNC POLICY                                                               ║
  # ╚──────────────────────────────────────────────────────────────────────────╝
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      # WHY: ServerSideApply=true is REQUIRED for kube-prometheus-stack CRDs
      # The Prometheus Operator CRDs have OpenAPI schemas that generate
      # annotations exceeding Kubernetes' 262KB limit for client-side apply.
      # Server-side apply bypasses this by tracking field ownership instead
      # of storing the full last-applied-configuration annotation.
      # Without this, ArgoCD sync fails with:
      # "metadata.annotations: Too long: may not be more than 262144 bytes"

