# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ Sealed Secrets Application                                                ║
# ║ Allows encrypted secrets in Git - only decryptable by this cluster        ║
# ║ WORKFLOW: Encrypt locally with kubeseal, commit to Git, deploy via ArgoCD ║
# ╚════════════════════════════════════════════════════════════════════════════╝

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  # ╔──────────────────────────────────────────────────────────────────────────╗
  # ║ SOURCE: Sealed Secrets Helm chart                                        ║
  # ╚──────────────────────────────────────────────────────────────────────────╝
  source:
    repoURL: https://github.com/headphonebear/homehill.git
    targetRevision: new_season
    path: clusters/apps/sealed-secrets/orchard
    # WHY: This path will contain:
    # - Chart.yaml (with sealed-secrets dependency)
    # - values.yaml (controller config, namespace scope, etc.)

    helm:
      releaseName: sealed-secrets

      valueFiles:
        - values.yaml

  # ╔──────────────────────────────────────────────────────────────────────────╗
  # ║ DESTINATION: kube-system namespace (standard for sealed-secrets)         ║
  # ╚──────────────────────────────────────────────────────────────────────────╝
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
    # WHY: Sealed Secrets controller traditionally lives in kube-system
    # This is the standard convention for this component

  # ╔──────────────────────────────────────────────────────────────────────────╗
  # ║ SYNC POLICY                                                               ║
  # ╚──────────────────────────────────────────────────────────────────────────╝
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=false
      # WHY: kube-system already exists, no need to create
