version: '3.8'

services:
  pihole:
    image: pihole/pihole:latest
    hostname: pihole
    ports:
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: udp
        mode: host
    environment:
      - TZ=Europe/Berlin
      - WEBPASSWORD=homehill # docker exec containername pihole setpassword 'homehill'
      - SERVERIP=192.168.1.101
      - DNS1=1.1.1.1
      - DNS2=1.0.0.1
    volumes:
      - pihole_etc:/etc/pihole
      - pihole_dnsmasq:/etc/dnsmasq.d
    networks:
      - traefik_traefik_proxy
      - pihole_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == dovecote
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_traefik_proxy"
        - "traefik.http.routers.pihole.rule=Host(`pihole.homehill.de`)"
        - "traefik.http.routers.pihole.entrypoints=websecure"
        - "traefik.http.routers.pihole.tls=true"
        - "traefik.http.routers.pihole.tls.certresolver=hetzner"
        - "traefik.http.services.pihole.loadbalancer.server.port=80"

networks:
  traefik_traefik_proxy:
    external: true
  pihole_network:
    driver: overlay
    attachable: true

volumes:
  pihole_etc:
  pihole_dnsmasq: