---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: memos-db-s3-backup
  namespace: memos
spec:
  encryptedData:
    ACCESS_KEY_ID: AgA3NBaA27mB3fl1SwU67O6x3ti7Z36LOZ3d0pTTc0+McgYuj+2UKVwPox9ddX2SJUlIUNC+sE5CdbKr6wnubP/+hDTR76FxisCA89EaV7Pc6K7BjLgxsjDYIiAEQXxgDbCaQE5j1CjJ6MxBX8B5aNMDFJa8f8YVUADKj1PiHppAL3MAQMENCCw8TDiD/ebnKvmiWWb5UhFCaR5bfP0CovARD/ghtIAHd2pzdqri0HC/ONIySAHZy/w5B/NuvOSAvTdNZr45epTE9IzzJ7aCnroT4VJPJxEmjfMorkyQApiZZ5r53MF51Wyqe7Zp/LIN/KBy3EhLvIeb4u+9J4GvZvBdsfjhiC7ejCpWRJXYlYYcesztQZiJRXukPtg6XZd8MTzYIv1TvWEMoPpFbZHeuxB6rLTA41PyllVgaiDFvvLo9LQsjEgJayeC5rLJae+cEyXOaVintuMtDXzpLMYmmTPKB1IeNW++//3Y8i6VS7zSjR5/XIJAPHibrqlXEh5kiYGcs11te0Qp5QObyHem7bteVFosYhgI7gUW6PCnNoX8WaC1qFoJg4SWDEzARxxtWMfXAVIpp+8iqztfygjeBHV48TAWtVl1U8vKy1mO1YoexS+NCctzTC5HZ34IpHpL8YLqdMCgx/WP+WgUtKDcbH3vz62fpMvQ3LQMpH6mLyQd0pEWKClVD4LpfMIgJEvSZoTUv3iB4csdhAR6dFBA3zkUqgio2g==
    ACCESS_SECRET_KEY: AgCK86CO1tUVSmPSI+xgVs5YrQnloWd0zNr0ePGKL7Ld+Bsj3vRYZ5Z5zuaIU4Q4KGo/Y/PJY3AbBMIeU4mfFt29qncv8Mv/HK8R9bwLKfk1N3wrAIz57AzcZwoyK6NxGk86go0n9z9JBwq4KMtvoAFGFpaJK5e3ZSuYJ2O3XjiFh9iIV2FAdRNjXm2jVJ0LuXG5lEIu0gpExYuw7qhXCfoCmnAe8PSvj/sjyIH+EoKbH46pHCbCAqF3GkD8PXkGNfXvcOPtz7XiR60vGQYtWA3jzRTQ636gMz17jXJueJ4YuDfkDdnyx0jHBz2zFwJ8U2J6QJPKfz+Z4PcszfNa2k8kCcQoHKf8XykbTjeHdOZ57uag2HBgkB50bXriaROX/a9YRa7L4QEBb/OUjCGkIGXrczDJGnA9N4D60Oncbde0+i/uHLo2tg6kpFsn5/hVE9Y7BsKZYixsEt5/1x0WJkF3Uh0UX1U7jDnkaKC+3fB+pz9DwS21MEI0/0Fuh1HzsyLOawRjRlHh4tI7S8Y42zawVzredOvTktc8SCrgYErOucf76RCM+wbOIjT3lGypYuEndkZDLU2UPbdkFjBmGH1BUe8/HmbCuPbxnSK1B8mN2NU696WiOhcYsYbV3bskZgSsf2WbkDjB5okaKFU0ks7Cic84Q50aTJNj4UVD5OuZAimfAUJ1JR0sHxuhdbpKMYV4FEuJPZv2Tks7TBwgBYlxWVw7N1wS5agYIl5Ur/uF2S+Xxtt9u8c6
  template:
    metadata:
      creationTimestamp: null
      name: memos-db-s3-backup
      namespace: memos
