apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-extras
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/headphonebear/homehill.git
    targetRevision: main
    path: clusters/orchard/apps/longhorn-extras
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
