---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: monitoring-grafana
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCHrJo2z1flV47e//ZwlHDUfPSavs+PVZIBBJlm4LBTNuFYDEpJNxmRn3gKkshLPZrfUZkiR2UXl3atyVm6UvHGG/kCo86ylzxRW5acFBbXBJXpzrhs/xmpnlMDtpiW+bguxGO8loD09lgWQPEbY5iZIxL/iZuimbk9eJp2D55qaZevoij+ABIiwbQa/KQ+035pbwif/1azjbO0F25eNebpuX44SMrgM3oQz1eRFvS5XkU8JzjaifFIEGZhlvDg4AlR318/QOp88+Wq/iR9LMc9IjnBqI5VC5S0qFUQtctS4Y1OpCNQEXMmQn7K/w/ERXJrFWn/KkiMNzczwK0MHbUK6X/ZXhUEhnmJn9M2bFL8sz3vALSj8jKk9jZAsv2EdSgq3fP+kLd0axplZf6Bf5NZwDF4w5Lbrd6b/X6JrtloJjcF4rMZS5EtG7rVzqLHfkdKTwEEq01Iw7bzzDhNNglnn9Vfy1ElVfy+l8rcJUjJNky5CS8W/6q+ksaI/mqUQBU2OEHPhKTTHFyx+F+CkP9rm/qad6hT8QDfSlVMf9j+s37HvER7lWDjNc6tZ9uq9SJyGm/GGrnwszTlfaCmhn2hIATRLfII9X6bisU1Dajtlc/RoDDalhg7dyThS8083Ghbad7OrFGMVcPpVxrag/u4pYj1H7l0fG/BgvKlZWz1Wf9aJ2CT9R4JczPRBA20WtPIwvh6zS2dB1NQhTg0hQ==
    admin-user: AgCeFRNdjRw3Z/GgG0/MOcP+9DM5NNpFvGj4GETHiTDmak+upsC6KM6wIZb5Lkpdg+/HT9AGuni7he4n33HhNA9N4R30KlZY5yA/fFQgLIA1mUpfN07aacDkW5RqVTT6pfiEa4pFtiVusPT7i1Da3EKohxvcxCrgsueE9J5iFEnjVvHUt1/80aM1/1po5EcfxSqMiqxCDAiQ7TCF6RoXxoq0jP37aLqGMBMX6XmoyBbzYBAj9DyXXX1wz6tswTayVq2Feg4eNxAtm6ffJOVA76xdNitSl3ifBwES1biKv56uYDQfQ5y16a9GNCpDDxY2jGvKtlzbItg4FrfpztU/jVQYW7HsVYpFYQao/Wm4GNq3zgrKob7IbcHKSIzA0eJ5B27qtTBoXcjfICfU6fxebgELoMZ48FuT+Vg5FAE9Ejys9Y5vlcxU6eS6CT0mo741EZm9NBJuzcSLqNB27yroqMMGOtHYkTxStYlVOb3ui5i2FaT4QyXoC6UwxXOdwwcFZQI7FjlCqBSMDfJ2UAusHMSJu1VomcSQqvkM7LF9rIQGAZHQ6t2Rd14YiF/HrU6/WrWikux3ePH+kyJndCxQ1vu7GpFjNutaH21e1CAylzxxv9AJrkz41rfFBmOvfsVvK+JVggeIBZw9E14jrWysVDpv4dV16rYyT5E2ydwTlrfYO+m2L13TuZw3DN6+U70G0THjYFvUYg==
  template:
    metadata:
      creationTimestamp: null
      name: monitoring-grafana
      namespace: monitoring
