# WHY: SealedSecrets sind verschlüsselte Secrets, die sicher in Git liegen können.
  # Der sealed-secrets Controller im Cluster hat den private key und kann sie
  # entschlüsseln. Nur der Controller kann das - niemand sonst, auch nicht jemand
  # der Zugriff auf das Git Repo hat.

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  # WHY: WICHTIG! Der Name muss "hetzner" sein (nicht hetzner-dns-token),
  # weil der ClusterIssuer nach einem Secret namens "hetzner" sucht.
  # Das war der Bug im alten Setup - Name-Mismatch zwischen Secret und Referenz.
  creationTimestamp: null
  name: hetzner
  namespace: cert-manager
spec:
  encryptedData:
    # WHY: Der Key muss "token" heißen (nicht api-key), weil der ClusterIssuer
    # nach "tokenSecretKeyRef.key: token" sucht. Name und Key müssen exakt
    # mit der ClusterIssuer Konfiguration übereinstimmen.
    #
    # ACHTUNG Bear: Dieser verschlüsselte Token ist vom ALTEN Cluster!
    # Wenn der neue Cluster einen anderen sealing-key hat, musst du das
    # Secret neu versiegeln mit: kubeseal --cert sealing-key.crt
    token: AgAVmvXT4cgd282dqbCY+Dvb1dO+qN8sBMbwG5Oq2+rVeNLNAg+BhaC6Q8J+udGmPU/KrWd8FzwHovYrwaXLmjLTuZjcsVEnyRQCKTqC2nRSlAwpxp5RE8xR1pNpTVeFDkpzJgPFnIXIkIVOhwQ1R72rEYrdFLpUas79XbU5w5BkOC5NSixFUOiJHX23B4YSrTPKIlrRGc4Wrz1MNcxZXOi/VutDoXrGFXqskCziDKV0a3bVKTQAiF5yrcJDCKvPoWebKz4cTGBxY3bHbRUWbhij32tCs1X3hEB4b/QZh5QVRszeq5NyTBfz/PL0tu/pnTgl2NYnAT4aGUD0ayxzAANBU9/MCkoqX8lUchEHfbg7njDSUK6U3r/o9CsZ7K4OzaanK+/mcbiKZ9iw6okIj5hx/i6c02C74755H5Me4S5OMoBC3EnKpUHpQbjh1jmir5WY0vRvT60fgdvwfVhirdiUB55aVm3+BzOkL7hXbOmGrMxsjxE9BeRNNoJ2vMXt9gk1O9NF9sA+Ybrvsvk9rD+niw+YtjvppngkDfBxsrI0qHBzSh/uTZVNcJdc5bxDYAA/Hc8gInJ04TkuP1cog2lZ3qKlT7Iurn1p6Y5CK9OeX3saDJ67fiThfwaMU31XRgTeAaSkPwIRTQSLWHa7WiDR+797leOrpFCJJdrnP0sU2JQlBibcyVFaVmpEIZETciUnHaCMXMAOcu4fQTfYjXKID0J1R9MzGPNdm6dH0L5Q3xMG4ezQM39ri/iKRObFRnvGRCbvfLTxY4WCvk1GgL4u
  template:
    metadata:
      creationTimestamp: null
      name: hetzner
      namespace: cert-manager
    type: Opaque
