# WHY: SealedSecrets sind verschlüsselte Secrets, die sicher in Git liegen können.
  # Der sealed-secrets Controller im Cluster hat den private key und kann sie
  # entschlüsseln. Nur der Controller kann das - niemand sonst, auch nicht jemand
  # der Zugriff auf das Git Repo hat.

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  # WHY: WICHTIG! Der Name muss "hetzner" sein (nicht hetzner-dns-token),
  # weil der ClusterIssuer nach einem Secret namens "hetzner" sucht.
  # Das war der Bug im alten Setup - Name-Mismatch zwischen Secret und Referenz.
  name: hetzner
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager-webhook-hetzner
    app.kubernetes.io/component: secret
spec:
  encryptedData:
    # WHY: Der Key muss "token" heißen (nicht api-key), weil der ClusterIssuer
    # nach "tokenSecretKeyRef.key: token" sucht. Name und Key müssen exakt
    # mit der ClusterIssuer Konfiguration übereinstimmen.
    #
    # ACHTUNG Bear: Dieser verschlüsselte Token ist vom ALTEN Cluster!
    # Wenn der neue Cluster einen anderen sealing-key hat, musst du das
    # Secret neu versiegeln mit: kubeseal --cert sealing-key.crt
    token: AgBRGduXptxlGq6ngmWOfwpWvoe2j3J0NPdqeYihD8J75/0sjfAEd2BURb8j2zT6jJzJ7sLiirgKbAT6giklX31Ickr3qUMn6P/FquLNbYFkxEMqJhINQiFm3dFP92swHvd6m5SNBrKkOasRTC6jBakRBySUKGSOWIP9uyUDtCDuprZd9bfCvmRX65AKd8+6CW0oirykgIbRwLHkGWGRWFAenVAFc26vy2TS0Sx5Lthqjq2PxV3SE/AGEAulAP+br9GB/5NscglJao7QzyfyLGPb1JGHtLqlZ4aeXi8e9PCqH7qBrxOQxLolMQ46seALSKXTl4eqOcshGqaM3P+4MiPyvzbw3l5oFzFVWXeq+9o4MnI02NMpLyI+Td5KD4XjQbD4X2+RCPP3rEFe+rEGREda/esBUiYF2RLj0pVKyLVWXRC55mMnADKvm+WLFCSZ2M343u+JZEWakfqgC2XJhkc4ialnEiUL4hHSqW7Pze14DgNQGaHk6NE3phw5b1drsCMbOcPziFF9d7QV8KqmZQ1F/INEJ+ttp7WSSMOmIET+yBOkvAbZr3nh33e8VTk7itOBIQPEwI0xtUjmJ5M2h6wclxR+3pnNEb/MdlXpjdQpygCPQaTB3XGgzWdCnucDNwS6biDHqDRujwY5UAlsHpvOfLe5lJTVMwqpkd97VwXQQ3+WgdTJgBCkmqY0gMFAMBhOxuT2rAPUYDNE8QFKumUlEWVAdIumemqRqXpoeNslDIwTBcNM8hmMK+8bngXIsatN/ehTVt+e/PON+aX0ohh1
  template:
    metadata:
      name: hetzner
      namespace: cert-manager
      labels:
        app.kubernetes.io/name: cert-manager-webhook-hetzner
