version: "3.8"

services:
  memos:
    image: ghcr.io/usememos/memos:latest
    user: "7001:7001"
    secrets:
      - memos_db_password
    entrypoint: ["/bin/sh", "-c"]
    # Debug Version - mit verbose logging
    command:
      - |
        export MEMOS_PASSWORD=$$(cat /run/secrets/memos_db_password)
        echo "=== Starting with explicit flags ==="
        ./memos \
          --driver postgres \
          --dsn "postgresql://homehill:$${MEMOS_PASSWORD}@postgres:5432/memos?sslmode=disable" \
          --port 5230 \
          --mode prod \
          --data /var/opt/memos
    volumes:
      - type: volume
        source: memos-data
        target: /var/opt/memos
        volume:
          nocopy: true
    networks:
      - traefik_traefik_proxy
      - postgres_database_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == greenhouse]  # <- Legacy constraint bleibt
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.memos.rule=Host(`memos.homehill.de`)"
        - "traefik.http.routers.memos.entrypoints=websecure"
        - "traefik.http.routers.memos.tls.certresolver=hetzner"
        - "traefik.http.services.memos.loadbalancer.server.port=5230"

volumes:
  memos-data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=forest.homehill.de,nolock,soft,rw,nfsvers=3"
      device: ":/nfs/memos/memos-svc" # path bc WD MyCloud NFS permission mapping

networks:
  traefik_traefik_proxy:
    external: true
  postgres_database_network:
    external: true

secrets:
  memos_db_password:
    external: true