version: "3.8"

services:
  memos:
    image: ghcr.io/usememos/memos:latest
    user: "7001:7001"
    secrets:
      - memos_db_password
    entrypoint: ["/bin/sh", "-c"]
    # Debug Version - mit verbose logging
    command:
      - |
        echo "=== DEBUG: Starting memos setup ==="
        echo "Environment vars:"
        env | grep MEMOS || echo "No MEMOS vars found"

        echo "=== Checking for memos binary ==="
        which memos && echo "Found memos in PATH" || echo "memos not in PATH"
        ls -la /app/memos 2>/dev/null && echo "Found /app/memos" || echo "No /app/memos"
        ls -la ./memos 2>/dev/null && echo "Found ./memos" || echo "No ./memos"

        echo "=== Setting up secrets ==="
        export MEMOS_PASSWORD=$$(cat /run/secrets/memos_db_password)
        echo "Password length: $${#MEMOS_PASSWORD}"

        echo "=== Final environment ==="
        export MEMOS_DRIVER=postgres
        export MEMOS_DSN="postgresql://homehill:$${MEMOS_PASSWORD}@postgres.homehill.de:5432/memos?sslmode=disable"
        echo "DSN set (length: $${#MEMOS_DSN})"

        echo "=== Attempting to exec ==="
        exec $$(which memos) || exec ./memos || exec /app/memos

    volumes:
      - type: volume
        source: memos-data
        target: /var/opt/memos
        volume:
          nocopy: true
    networks:
      - traefik_traefik_proxy
      - postgres_database_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == greenhouse]  # <- Legacy constraint bleibt
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.memos.rule=Host(`memos.homehill.de`)"
        - "traefik.http.routers.memos.entrypoints=websecure"
        - "traefik.http.routers.memos.tls.certresolver=hetzner"
        - "traefik.http.services.memos.loadbalancer.server.port=5230"

volumes:
  memos-data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=forest.homehill.de,nolock,soft,rw,nfsvers=3"
      device: ":/nfs/memos/memos-svc" # path bc WD MyCloud NFS permission mapping

networks:
  traefik_traefik_proxy:
    external: true
  postgres_database_network:
    external: true

secrets:
  memos_db_password:
    external: true