version: '3.8'

services:
  postgres:
    image: postgres:16
    secrets:
      - postgres_password
    environment:
      - POSTGRES_USER=homehill
      - POSTGRES_DB=homehill
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - database_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == nook
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U homehill"]
      interval: 10s
      timeout: 5s
      retries: 5

secrets:
  postgres_password:
    external: true

networks:
  database_network:
    driver: overlay
    attachable: true

volumes:
  postgres_data:
